
GET http://localhost:4004/odata/v4/product/printHelloWorld(input='Nothing')

GET http://localhost:4004/odata/v4/product/addition(n1=1,n2=20)

GET http://localhost:4004/odata/v4/product/Bike(category='Mountain')

//rest syntax

GET http://localhost:4004/rest/product/Bike(category='1')